#539 Ensure that duplicate Places cannot be added using the importer
Terrastories/terrastories pull request #551
Opened 2020-10-19 20:04 UTC by jaimevelaz

_Fixes_ https://github.com/Terrastories/terrastories/issues/539

This PR adds a spec to ensure places cannot be duplicated through the `Place` importer, if I understood correctly the issue the csv importer was already ensuring a single Place with same attributes is created by using `place = Place.find_or_create_by(decorator.to_h)` in line https://github.com/Terrastories/terrastories/blob/master/rails/app/models/place.rb#L17

2020-10-26 01:01 UTC, FeminismIsAwesome commented
@jaimevelaz i'm seeing a test, but it doesn't seem like the contents of the spec match the assertion, and missing the passing behavior to go with?

2020-10-26 01:02 UTC, FeminismIsAwesome requested changes
make the test red-green by adding the behavior of not creating 2 on duplicates instead of just asserting 1 on creation, and fix importer code

2020-10-26 01:53 UTC, jaimevelaz commented
Thanks for the review @FeminismIsAwesome, I'll take another look to it, initially I thought building a CSV with two identical lines and asserting a single place is created would be enough to validate the defined behaviour but I'm probably missing something.

2020-10-27 16:37 UTC, jaimevelaz commented
> make the test red-green by adding the behavior of not creating 2 on duplicates instead of just asserting 1 on creation, and fix importer code

I've changed the spec to make it easier to read and understand. Feedback is welcome @FeminismIsAwesome

2020-10-27 20:12 UTC, FeminismIsAwesome approved these changes
awesome! merging.

2020-10-27 20:12 UTC, merged