Fix map marker filtering
Terrastories/terrastories pull request #612
Opened 2021-03-07 11:37 UTC by astojanowski

Fixes #597

- Added updating of markers source each time the list of places has
changed (e.g. by filtering),
- Removed duplicates from the list of places. When there are two stories
happening at the same place, the place doesn't have to be added twice.

2021-04-19 14:41 UTC, lauramosher commented
Thank you so much for your contribution! We really appreciate it. We'll be reviewing this soon.

2021-09-10 19:18 UTC, rudokemper requested changes
Looks so great! Sorry for the delay on this. Would you mind resolving the conflicts from the other PR you submitted before merging?

2021-09-10 19:25 UTC, rudokemper approved these changes

2021-09-10 19:25 UTC, rudokemper commented
Went ahead and did it; thanks for these great PRs @astojanowski and sorry it took a while to get them approved / merged.

2021-09-10 19:26 UTC, merged