foreman procfile fixes
Terrastories/terrastories pull request #911
Opened 2023-04-30 10:52 UTC by albertchae

- Respect PORT from compose.yaml in Procfile.dev
- Add foreman in gemfile and use bundle exec to run it

2023-04-30 10:55 UTC, albertchae commented on rails/Gemfile.lock
> +  aarch64-linux-musl
not sure where this change is coming from

2023-04-30 10:55 UTC, albertchae commented on rails/Gemfile.lock
> +   ruby 2.7.8p225
Looks like this updated here finally https://github.com/Terrastories/terrastories/pull/910#issuecomment-1528829225

2023-05-01 15:05 UTC, lauramosher requested changes
Let's remove the `foreman` gem, delete the lock file, and re-bundle.

Removing the unset on the PORT seems like a good idea. Ideally, foreman and the dev Procfile are only used by developers working on offline mode or standard. Official offline setup should be done using the appropriate flags so the Procfile is not being used. Either way, though, the removal seems like a good idea though!

2023-05-01 15:05 UTC, lauramosher commented on rails/Gemfile
> +  gem "foreman"
Per `foreman`'s installation instructions, this gem [should NOT be installed in the Gemfile](https://github.com/ddollar/foreman#installation).

2023-05-01 15:05 UTC, lauramosher commented on rails/bin/dev
> -exec foreman start -f Procfile.dev "$@"
This setup was done in this manner for a reason. See the `foreman` gem notes above.

2024-04-12 15:18 UTC, closed without merging